server:
  port: 8085
feign:
  okhttp:
    enabled: true   # 开启OKHttp连接池支持
hm:
  db:
    database: hm-trade
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller
spring:
  rabbitmq:
    host: 192.168.100.128 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123456 # 密码